# Data preparation

In [ ]:
import numpy as np

## LTC preprocessing

In [ ]:
dataset_LTC = np.load("/content/drive/MyDrive/unipoint/dataset_LTC.npy", allow_pickle = True)
dataset_LTC

array([[3.60470000e+04, 3.60470000e+04, 0.00000000e+00],
       [4.18310000e+04, 7.78780000e+04, 0.00000000e+00],
       [1.51073000e+05, 2.28951000e+05, 0.00000000e+00],
       ...,
       [4.12810000e+04, 3.15356062e+10, 0.00000000e+00],
       [2.04746000e+05, 3.15358109e+10, 0.00000000e+00],
       [1.71130000e+04, 3.15358280e+10, 1.00000000e+00]])

In [ ]:
# drop 'time from 0' column
dataset_LTC = np.delete(dataset_LTC, 1, axis = 1)
dataset_LTC

array([[3.60470e+04, 0.00000e+00],
       [4.18310e+04, 0.00000e+00],
       [1.51073e+05, 0.00000e+00],
       ...,
       [4.12810e+04, 0.00000e+00],
       [2.04746e+05, 0.00000e+00],
       [1.71130e+04, 1.00000e+00]])

In [ ]:
dataset_LTC = np.transpose(dataset_LTC)
dataset_LTC

array([[3.60470e+04, 4.18310e+04, 1.51073e+05, ..., 4.12810e+04,
        2.04746e+05, 1.71130e+04],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00]])

In [ ]:
dataset_LTC.shape[1]

901989

In [ ]:
time_LTC_zeros = []
time_LTC_ones = []

# for converting miliseconds to seconds in the first raws it is needed to divide values by 1000

for i in range(dataset_LTC.shape[1]):
  if dataset_LTC[1,i] == 0:
    time_LTC_zeros.append(dataset_LTC[0,i]/1000)
  elif dataset_LTC[1,i] == 1:
    time_LTC_ones.append(dataset_LTC[0,i]/1000)

line_zeros = np.zeros_like(time_LTC_zeros)
line_ones = np.ones_like(time_LTC_ones)

dataset_zeros = np.array([time_LTC_zeros, line_zeros])
dataset_ones = np.array([time_LTC_ones, line_ones])

print(dataset_zeros)
print()
print(dataset_ones)

[[ 36.047  41.831 151.073 ...  14.893  41.281 204.746]
 [  0.      0.      0.    ...   0.      0.      0.   ]]

[[ 98.221  57.206  38.969 ...  52.958 108.255  17.113]
 [  1.      1.      1.    ...   1.      1.      1.   ]]


In [ ]:
dataset_zeros.shape

(2, 461927)

In [ ]:
dataset_ones.shape

(2, 440062)

In [ ]:
# now we need to divide prepared data into train:val:test = 60:20:20
proportion_zeros = [int(0.6 * dataset_zeros.shape[1]), int(0.8 * dataset_zeros.shape[1])]
proportion_ones = [int(0.6 * dataset_ones.shape[1]), int(0.8 * dataset_ones.shape[1])]

# cut zeros dataset into the train, val and test
dataset_zeros_split = np.hsplit(dataset_zeros, proportion_zeros)
dataset_ones_split = np.hsplit(dataset_ones, proportion_ones)

In [ ]:
num_seq = 3319 # num of sequences in every future batch

# FOR ZEROS
for part_idx, part in enumerate(dataset_zeros_split):
  print(part_idx, part)
  
  # cut each part (train, val, test) into the 'num_seq' length
  cut_zeros = [i for i in range(0, part.shape[1], num_seq)]
  dataset_zeros_cut = np.hsplit(part, cut_zeros)
  # removing unneeded stuff
  dataset_zeros_cut.pop(0)
  dataset_zeros_cut.pop(-1)

  # recording all the values 
  for cut_idx, cut in enumerate(dataset_zeros_cut):
    if part_idx == 0:
      np.save('/content/drive/MyDrive/unipoint/data/data_LTC/train_LTC/train_LTC_zeros_' + str(cut_idx) + '.npy', cut)
    if part_idx == 1:
      np.save('/content/drive/MyDrive/unipoint/data/data_LTC/val_LTC/val_LTC_zeros_' + str(cut_idx) + '.npy', cut)
    if part_idx == 2:
      np.save('/content/drive/MyDrive/unipoint/data/data_LTC/test_LTC/test_LTC_zeros_' + str(cut_idx) + '.npy', cut)

# FOR ONES
for part_idx, part in enumerate(dataset_ones_split):
  print(part_idx, part)
  
  # cut each part (train, val, test) into the 'num_seq' length
  cut_ones = [i for i in range(0, part.shape[1], num_seq)]
  dataset_ones_cut = np.hsplit(part, cut_ones)
  # removing unneeded stuff
  dataset_ones_cut.pop(0)
  dataset_ones_cut.pop(-1)

  # recording all the values 
  for cut_idx, cut in enumerate(dataset_ones_cut):
    if part_idx == 0:
      np.save('/content/drive/MyDrive/unipoint/data/data_LTC/train_LTC/train_LTC_ones_' + str(cut_idx) + '.npy', cut)
    if part_idx == 1:
      np.save('/content/drive/MyDrive/unipoint/data/data_LTC/val_LTC/val_LTC_ones_' + str(cut_idx) + '.npy', cut)
    if part_idx == 2:
      np.save('/content/drive/MyDrive/unipoint/data/data_LTC/test_LTC/test_LTC_ones_' + str(cut_idx) + '.npy', cut)


0 [[ 36.047  41.831 151.073 ...   9.797  10.335  38.561]
 [  0.      0.      0.    ...   0.      0.      0.   ]]
1 [[ 3.959  9.322 27.339 ... 59.167 32.848 12.369]
 [ 0.     0.     0.    ...  0.     0.     0.   ]]
2 [[  3.142  10.755   9.834 ...  14.893  41.281 204.746]
 [  0.      0.      0.    ...   0.      0.      0.   ]]
0 [[98.221 57.206 38.969 ... 21.887 34.529 12.957]
 [ 1.     1.     1.    ...  1.     1.     1.   ]]
1 [[ 24.981   9.455  10.907 ... 129.162 175.393  71.247]
 [  1.      1.      1.    ...   1.      1.      1.   ]]
2 [[101.371 129.248  88.038 ...  52.958 108.255  17.113]
 [  1.      1.      1.    ...   1.      1.      1.   ]]


## EOS preprocessing

In [ ]:
dataset_EOS = np.load("/content/drive/MyDrive/unipoint/dataset_EOS.npy", allow_pickle = True)


# drop 'time from 0' column
dataset_EOS = np.delete(dataset_EOS, 1, axis = 1)
dataset_EOS = np.transpose(dataset_EOS)

time_EOS_zeros = []
time_EOS_ones = []

# for converting miliseconds to seconds in the first raws it is needed to divide values by 1000

for i in range(dataset_EOS.shape[1]):
  if dataset_EOS[1,i] == 0:
    time_EOS_zeros.append(dataset_EOS[0,i]/1000)
  elif dataset_EOS[1,i] == 1:
    time_EOS_ones.append(dataset_EOS[0,i]/1000)

line_zeros = np.zeros_like(time_EOS_zeros)
line_ones = np.ones_like(time_EOS_ones)

dataset_zeros = np.array([time_EOS_zeros, line_zeros])
dataset_ones = np.array([time_EOS_ones, line_ones])

print(dataset_zeros)
print()
print(dataset_ones)

dataset_zeros.shape
dataset_ones.shape

# now we need to divide prepared data into train:val:test = 60:20:20
proportion_zeros = [int(0.6 * dataset_zeros.shape[1]), int(0.8 * dataset_zeros.shape[1])]
proportion_ones = [int(0.6 * dataset_ones.shape[1]), int(0.8 * dataset_ones.shape[1])]

# cut zeros dataset into the train, val and test
dataset_zeros_split = np.hsplit(dataset_zeros, proportion_zeros)
dataset_ones_split = np.hsplit(dataset_ones, proportion_ones)
num_seq = 3319 # num of sequences in every future batch

# FOR ZEROS
for part_idx, part in enumerate(dataset_zeros_split):
  print(part_idx, part)
  
  # cut each part (train, val, test) into the 'num_seq' length
  cut_zeros = [i for i in range(0, part.shape[1], num_seq)]
  dataset_zeros_cut = np.hsplit(part, cut_zeros)
  # removing unneeded stuff
  dataset_zeros_cut.pop(0)
  dataset_zeros_cut.pop(-1)

  # recording all the values 
  for cut_idx, cut in enumerate(dataset_zeros_cut):
    if part_idx == 0:
      np.save('/content/drive/MyDrive/unipoint/data/data_EOS/train_EOS/train_EOS_zeros_' + str(cut_idx) + '.npy', cut)
    if part_idx == 1:
      np.save('/content/drive/MyDrive/unipoint/data/data_EOS/val_EOS/val_EOS_zeros_' + str(cut_idx) + '.npy', cut)
    if part_idx == 2:
      np.save('/content/drive/MyDrive/unipoint/data/data_EOS/test_EOS/test_EOS_zeros_' + str(cut_idx) + '.npy', cut)

# FOR ONES
for part_idx, part in enumerate(dataset_ones_split):
  print(part_idx, part)
  
  # cut each part (train, val, test) into the 'num_seq' length
  cut_ones = [i for i in range(0, part.shape[1], num_seq)]
  dataset_ones_cut = np.hsplit(part, cut_ones)
  # removing unneeded stuff
  dataset_ones_cut.pop(0)
  dataset_ones_cut.pop(-1)

  # recording all the values 
  for cut_idx, cut in enumerate(dataset_ones_cut):
    if part_idx == 0:
      np.save('/content/drive/MyDrive/unipoint/data/data_EOS/train_EOS/train_EOS_ones_' + str(cut_idx) + '.npy', cut)
    if part_idx == 1:
      np.save('/content/drive/MyDrive/unipoint/data/data_EOS/val_EOS/val_EOS_ones_' + str(cut_idx) + '.npy', cut)
    if part_idx == 2:
      np.save('/content/drive/MyDrive/unipoint/data/data_EOS/test_EOS/test_EOS_ones_' + str(cut_idx) + '.npy', cut)


[[  56.914   11.428   29.426 ...  516.549  177.156 1362.134]
 [   0.       0.       0.    ...    0.       0.       0.   ]]

[[ 17.598  14.441  96.329 ... 488.478 128.664 990.835]
 [  1.      1.      1.    ...   1.      1.      1.   ]]
0 [[56.914 11.428 29.426 ... 17.61  18.524 12.906]
 [ 0.     0.     0.    ...  0.     0.     0.   ]]
1 [[  6.752  11.854  12.483 ... 110.148  60.012  50.523]
 [  0.      0.      0.    ...   0.      0.      0.   ]]
2 [[  95.326   73.795   74.946 ...  516.549  177.156 1362.134]
 [   0.       0.       0.    ...    0.       0.       0.   ]]
0 [[17.598 14.441 96.329 ...  9.933  9.367 30.375]
 [ 1.     1.     1.    ...  1.     1.     1.   ]]
1 [[16.38  25.336 11.403 ...  2.116  3.948  6.946]
 [ 1.     1.     1.    ...  1.     1.     1.   ]]
2 [[ 13.006  25.64   10.156 ... 488.478 128.664 990.835]
 [  1.      1.      1.    ...   1.      1.      1.   ]]


## ETH preprocessing

In [ ]:
dataset_ETH = np.load("/content/drive/MyDrive/unipoint/dataset_filtered_ETH.npy", allow_pickle = True)
print(dataset_ETH.shape)
dataset_ETH

(527, 3000, 3)


array([[[1.42720000e+04, 1.42720000e+04, 1.00000000e+00],
        [1.33890000e+04, 2.76610000e+04, 0.00000000e+00],
        [2.73870000e+04, 5.50480000e+04, 0.00000000e+00],
        ...,
        [1.13620000e+04, 7.58121140e+07, 0.00000000e+00],
        [2.33570000e+04, 7.58354710e+07, 0.00000000e+00],
        [7.34500000e+03, 7.58428160e+07, 1.00000000e+00]],

       [[1.48670000e+04, 7.58576830e+07, 1.00000000e+00],
        [2.38870000e+04, 7.58815700e+07, 1.00000000e+00],
        [5.42900000e+03, 7.58869990e+07, 1.00000000e+00],
        ...,
        [1.23110000e+04, 1.21968785e+08, 0.00000000e+00],
        [1.87530000e+04, 1.21987538e+08, 1.00000000e+00],
        [1.44190000e+04, 1.22001957e+08, 1.00000000e+00]],

       [[8.20800000e+03, 1.22010165e+08, 0.00000000e+00],
        [4.40500000e+03, 1.22014570e+08, 0.00000000e+00],
        [9.40300000e+03, 1.22023973e+08, 0.00000000e+00],
        ...,
        [5.06200000e+03, 1.49642586e+08, 1.00000000e+00],
        [3.09500000e+03, 1.49

In [ ]:
# drop 'time from 0' column
dataset_ETH = np.delete(dataset_ETH[:,:,], 1, axis = 2)
dataset_ETH = dataset_ETH.reshape(-1,2)
dataset_ETH = np.transpose(dataset_ETH)

In [ ]:
dataset_ETH

array([[1.4272e+04, 1.3389e+04, 2.7387e+04, ..., 5.2950e+03, 9.3470e+03,
        8.6780e+03],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 1.0000e+00,
        1.0000e+00]])

In [ ]:
time_ETH_zeros = []
time_ETH_ones = []

# for converting miliseconds to seconds in the first raws it is needed to divide values by 1000

for i in range(dataset_ETH.shape[1]):
  if dataset_ETH[1,i] == 0:
    time_ETH_zeros.append(dataset_ETH[0,i]/1000)
  elif dataset_ETH[1,i] == 1:
    time_ETH_ones.append(dataset_ETH[0,i]/1000)

line_zeros = np.zeros_like(time_ETH_zeros)
line_ones = np.ones_like(time_ETH_ones)

dataset_zeros = np.array([time_ETH_zeros, line_zeros])
dataset_ones = np.array([time_ETH_ones, line_ones])

print(dataset_zeros)
print()
print(dataset_ones)

dataset_zeros.shape
dataset_ones.shape

# now we need to divide prepared data into train:val:test = 60:20:20
proportion_zeros = [int(0.6 * dataset_zeros.shape[1]), int(0.8 * dataset_zeros.shape[1])]
proportion_ones = [int(0.6 * dataset_ones.shape[1]), int(0.8 * dataset_ones.shape[1])]

# cut zeros dataset into the train, val and test
dataset_zeros_split = np.hsplit(dataset_zeros, proportion_zeros)
dataset_ones_split = np.hsplit(dataset_ones, proportion_ones)
num_seq = 3319 # num of sequences in every future batch

# FOR ZEROS
for part_idx, part in enumerate(dataset_zeros_split):
  print(part_idx, part)
  
  # cut each part (train, val, test) into the 'num_seq' length
  cut_zeros = [i for i in range(0, part.shape[1], num_seq)]
  dataset_zeros_cut = np.hsplit(part, cut_zeros)
  # removing unneeded stuff
  dataset_zeros_cut.pop(0)
  dataset_zeros_cut.pop(-1)

  # recording all the values 
  for cut_idx, cut in enumerate(dataset_zeros_cut):
    if part_idx == 0:
      np.save('/content/drive/MyDrive/unipoint/data/data_ETH/train_ETH/train_ETH_zeros_' + str(cut_idx) + '.npy', cut)
    if part_idx == 1:
      np.save('/content/drive/MyDrive/unipoint/data/data_ETH/val_ETH/val_ETH_zeros_' + str(cut_idx) + '.npy', cut)
    if part_idx == 2:
      np.save('/content/drive/MyDrive/unipoint/data/data_ETH/test_ETH/test_ETH_zeros_' + str(cut_idx) + '.npy', cut)

# FOR ONES
for part_idx, part in enumerate(dataset_ones_split):
  print(part_idx, part)
  
  # cut each part (train, val, test) into the 'num_seq' length
  cut_ones = [i for i in range(0, part.shape[1], num_seq)]
  dataset_ones_cut = np.hsplit(part, cut_ones)
  # removing unneeded stuff
  dataset_ones_cut.pop(0)
  dataset_ones_cut.pop(-1)

  # recording all the values 
  for cut_idx, cut in enumerate(dataset_ones_cut):
    if part_idx == 0:
      np.save('/content/drive/MyDrive/unipoint/data/data_ETH/train_ETH/train_ETH_ones_' + str(cut_idx) + '.npy', cut)
    if part_idx == 1:
      np.save('/content/drive/MyDrive/unipoint/data/data_ETH/val_ETH/val_ETH_ones_' + str(cut_idx) + '.npy', cut)
    if part_idx == 2:
      np.save('/content/drive/MyDrive/unipoint/data/data_ETH/test_ETH/test_ETH_ones_' + str(cut_idx) + '.npy', cut)


[[13.389 27.387 11.675 ...  9.016 21.031  5.295]
 [ 0.     0.     0.    ...  0.     0.     0.   ]]

[[14.272 12.05  16.608 ... 12.158  9.347  8.678]
 [ 1.     1.     1.    ...  1.     1.     1.   ]]
0 [[13.389 27.387 11.675 ... 34.997 13.486 16.646]
 [ 0.     0.     0.    ...  0.     0.     0.   ]]
1 [[21.735 31.121 14.594 ... 20.837 69.819 22.316]
 [ 0.     0.     0.    ...  0.     0.     0.   ]]
2 [[25.528 25.284  6.598 ...  9.016 21.031  5.295]
 [ 0.     0.     0.    ...  0.     0.     0.   ]]
0 [[14.272 12.05  16.608 ... 12.433 27.342 13.361]
 [ 1.     1.     1.    ...  1.     1.     1.   ]]
1 [[25.574  8.531 39.553 ... 25.434 44.177 19.299]
 [ 1.     1.     1.    ...  1.     1.     1.   ]]
2 [[46.535 33.063 26.747 ... 12.158  9.347  8.678]
 [ 1.     1.     1.    ...  1.     1.     1.   ]]


## Data with bids preprocessing

In [ ]:
dataset_transact = np.load("/content/drive/MyDrive/unipoint/transact_dataset_ETH.npy", allow_pickle = True)
dataset_transact

array([[          0,           0,           1],
       [        477,         477,           0],
       [       1176,         699,           1],
       ...,
       [31535986960,        8189,           1],
       [31535992147,        5187,           1],
       [31535995183,        3036,           1]])

In [ ]:
# drop 'time from 0' column
dataset_transact = np.delete(dataset_transact, 0, axis = 1)
dataset_transact = np.transpose(dataset_transact)

time_transact_zeros = []
time_transact_ones = []

# for converting miliseconds to seconds in the first raws it is needed to divide values by 1000

for i in range(dataset_transact.shape[1]):
  if dataset_transact[1,i] == 0:
    time_transact_zeros.append(dataset_transact[0,i]/1000)
  elif dataset_transact[1,i] == 1:
    time_transact_ones.append(dataset_transact[0,i]/1000)

line_zeros = np.zeros_like(time_transact_zeros)
line_ones = np.ones_like(time_transact_ones)

dataset_zeros = np.array([time_transact_zeros, line_zeros])
dataset_ones = np.array([time_transact_ones, line_ones])

print(dataset_zeros)
print()
print(dataset_ones)

dataset_zeros.shape
dataset_ones.shape

# now we need to divide prepared data into train:val:test = 60:20:20
proportion_zeros = [int(0.6 * dataset_zeros.shape[1]), int(0.8 * dataset_zeros.shape[1])]
proportion_ones = [int(0.6 * dataset_ones.shape[1]), int(0.8 * dataset_ones.shape[1])]

# cut zeros dataset into the train, val and test
dataset_zeros_split = np.hsplit(dataset_zeros, proportion_zeros)
dataset_ones_split = np.hsplit(dataset_ones, proportion_ones)
num_seq = 3319 # num of sequences in every future batch

# FOR ZEROS
for part_idx, part in enumerate(dataset_zeros_split):
  print(part_idx, part)
  
  # cut each part (train, val, test) into the 'num_seq' length
  cut_zeros = [i for i in range(0, part.shape[1], num_seq)]
  dataset_zeros_cut = np.hsplit(part, cut_zeros)
  # removing unneeded stuff
  dataset_zeros_cut.pop(0)
  dataset_zeros_cut.pop(-1)

  # recording all the values 
  for cut_idx, cut in enumerate(dataset_zeros_cut):
    if part_idx == 0:
      np.save('/content/drive/MyDrive/unipoint/data/data_transact/train_transact/train_transact_zeros_' + str(cut_idx) + '.npy', cut)
    if part_idx == 1:
      np.save('/content/drive/MyDrive/unipoint/data/data_transact/val_transact/val_transact_zeros_' + str(cut_idx) + '.npy', cut)
    if part_idx == 2:
      np.save('/content/drive/MyDrive/unipoint/data/data_transact/test_transact/test_transact_zeros_' + str(cut_idx) + '.npy', cut)

# FOR ONES
for part_idx, part in enumerate(dataset_ones_split):
  print(part_idx, part)
  
  # cut each part (train, val, test) into the 'num_seq' length
  cut_ones = [i for i in range(0, part.shape[1], num_seq)]
  dataset_ones_cut = np.hsplit(part, cut_ones)
  # removing unneeded stuff
  dataset_ones_cut.pop(0)
  dataset_ones_cut.pop(-1)

  # recording all the values 
  for cut_idx, cut in enumerate(dataset_ones_cut):
    if part_idx == 0:
      np.save('/content/drive/MyDrive/unipoint/data/data_transact/train_transact/train_transact_ones_' + str(cut_idx) + '.npy', cut)
    if part_idx == 1:
      np.save('/content/drive/MyDrive/unipoint/data/data_transact/val_transact/val_transact_ones_' + str(cut_idx) + '.npy', cut)
    if part_idx == 2:
      np.save('/content/drive/MyDrive/unipoint/data/data_transact/test_transact/test_transact_ones_' + str(cut_idx) + '.npy', cut)


[[0.477 0.68  2.179 ... 2.119 4.656 8.042]
 [0.    0.    0.    ... 0.    0.    0.   ]]

[[0.    0.699 0.818 ... 8.189 5.187 3.036]
 [1.    1.    1.    ... 1.    1.    1.   ]]
0 [[0.477 0.68  2.179 ... 0.112 0.817 0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]]
1 [[0.635 0.144 0.08  ... 0.276 0.204 0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]]
2 [[0.    1.193 1.02  ... 2.119 4.656 8.042]
 [0.    0.    0.    ... 0.    0.    0.   ]]
0 [[0.    0.699 0.818 ... 0.    0.433 0.137]
 [1.    1.    1.    ... 1.    1.    1.   ]]
1 [[0.343 0.153 0.211 ... 0.311 0.212 1.005]
 [1.    1.    1.    ... 1.    1.    1.   ]]
2 [[0.886 1.758 0.679 ... 8.189 5.187 3.036]
 [1.    1.    1.    ... 1.    1.    1.   ]]
